### ISSUE TITLE
Fetching related Entries

### ISSUE THREAD

**Issue by sgalonska** [bolt/jsonaccess#3]
I could not figure out how to fetch related entries through the JSON API. In my case I have a relation between "photos" and "persons". Each person can have n photos. Fetching all photos through
```
GET /json/photos
````
is easy. But I need to filter by the related person id. Does anyone have an idea?

**Comment by tobias2k** [comment]
Original jsonaccess author here.

It's been a while, but IIRC, I didn't design jsonaccess to handle
relations at all, and AFAIK nobody else has added this feature (yet). It
shouldn't be too hard, just needs to be implemented.

Something like this would be nice:

GET /json/person/27/photos

I'd have to check how Symfony's routing fits into the picture; it's
definitely possible, but might be a bit of a kludge *cough*regular
expressions*cough*.

On Tue, Feb 17, 2015 at 08:33:47AM -0800, Sebastian Galonska wrote:
> I could not figure out how to fetch related entries through the JSON
> API. In my case I have a relation between "photos" and "persons". Each
> person can have n photos. Fetching all photos through
> ```
> GET /json/photos
> ````
> is easy. But I need to filter by the related person id. Does anyone have an idea?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/jsonaccess/issues/3

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by sgalonska** [comment]
Thanks for getting back to me. you confirmed what I was afraid of. Will look into it, but it could take some while. But one question remains: is bolt aware of the relations in any way and can we use it to our advantage or do we have to filter ALL results in software and not in the db?
