### ISSUE TITLE
Paging does not work

### ISSUE THREAD

**Issue by milesj** [bolt/jsonaccess#4]
I'm using Bolt 2.0.6 and JsonAccess 1.0. Anytime I try and page, it returns the same records over and over. For example, if I have 15 records in a contenttype, the first query `?page=1&limit=5` will return the first 5 records. The second query `?page=2&limit=5` will return the same 5 records instead of 5 new records.

**Comment by milesj** [comment]
After some debugging, it looks like adding `$options['paging'] = true;` before calling `getContent()` fixes the problem.

**Comment by milesj** [comment]
Thanks for the merge! Any idea why the extension still shows 1.0.0? Won't allow me to upgrade.

**Comment by GawainLynch** [comment]
Bolt v2.0.x locks the version in `extensions/composer.json`.

There are three ways to move forward:
1. Edit `extensions/composer.json`. and in the part where you see `"bolt/jsonaccess" : "1.0.0"` you change `1.0.0` to `~1.0`
2. Upgrade to Bolt 2.1.3 (or later for anyone else reading this in the future) and there will be a "Versions" button you can use to select newer/older versions
3. Uninstall the extension, and just reinstall and chose 1.0.1

**Comment by milesj** [comment]
Ah, that's a bit odd. Thanks for the info!

**Comment by GawainLynch** [comment]
BTW, either one of those are options… you don't need to do all 3.
